name: Send Release Notes via Gmail SMTP

on:
  release:
    types: [published]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set release notes environment variable
        run: echo "RELEASE_BODY<<EOF"$'\n'"${{ github.event.release.body }}"$'\n'EOF >> $GITHUB_ENV

      - name: Send release notes email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "New Release: ${{ github.event.release.name }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          content_type: text/html
          body: |
            <h2>Release: ${{ github.event.release.name }}</h2>
            <p>${{ env.RELEASE_BODY }}</p>
            <p><a href="${{ github.event.release.html_url }}">View Release on GitHub</a></p>
