name: Send Release Notes

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes
        run: |
          git log -n 10 --pretty=format:"- %s" > release_notes.txt

      - name: Send release notes email
        uses: /action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Release Notes"
          body: ${{ steps.release_notes.outputs.notes }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: "pri39849@gmail.com"
